package com.baranov.javacourse.controller;

import com.baranov.javacourse.entity.Film;
import com.baranov.javacourse.repo.FilmRepo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
public class UserController {

    @GetMapping("/greeting")
    public String greeting(@RequestParam(name="name", required=false, defaultValue="World") String name, Model model) {
        model.addAttribute("name", name);
        return "greeting.mustache";
    }

    @Controller    // This means that this class is a Controller
    @RequestMapping(path="/main") // This means URL's start with /demo (after Application path)
    public class MainController {
        @Autowired // This means to get the bean called userRepository
        // Which is auto-generated by Spring, we will use it to handle the data
        private FilmRepo filmRepo;

        @GetMapping(path = "/add-film") // Map ONLY GET Requests
        public @ResponseBody
        String addNewFilm(@RequestParam String title, @RequestParam String genre, Integer year) {
            // @ResponseBody means the returned String is the response, not a view name
            // @RequestParam means it is a parameter from the GET or POST request

            Film film = new Film();
            film.setTitle(title);
            film.setGenre(genre);
            film.setYear(year);
            return "Saved";
        }
    }
}

